### ISSUE TITLE
ENS

### ISSUE THREAD

**Issue by cjh20000613** [WTFAcademy/WTF-Ethers#63]
Error: ENS name not configured (operation="resolveName(\"vitalik.eth\")", code=UNSUPPORTED_OPERATION, version=providers/5.6.8)
    at Logger.makeError (D:\vs\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (D:\vs\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at FallbackProvider.<anonymous> (D:\vs\node_modules\@ethersproject\providers\lib\base-provider.js:1970:36)
    at step (D:\vs\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (D:\vs\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)      
    at fulfilled (D:\vs\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)        
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'ENS name not configured',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'resolveName("vitalik.eth")'
}

**Comment by AmazingAng** [comment]
用的哪个ethers版本

**Comment by cjh20000613** [comment]
突然就能输出了

**Comment by cjh20000613** [comment]
> 突然就能输出了

可能网络问题吧，有时能输出，有时又报错
